# Generated by scripts/update.sh from Valve's client manifest. Do not edit.
{
  channel = "publicbeta";
  version = "1791592380";
  baseUrl = "https://client-update.fastly.steamstatic.com";
  components = {
    tenfoot_images_all = {
      file = "tenfoot_images_all.zip.86419c7a56c12dd107b5e0d46f50c8a9b121f3cc";
      sha256 = "990676bc29d01736477c6b571b5048258a6156284ef242503112fc68567cbf01";
    };
    steamui_websrc_all = {
      file = "steamui_websrc_all.zip.7978dcd03edc981408b32dcbc5571be478f62a81";
      sha256 = "8c5ef5bf60a6dcefe7f45587c14da57579fa0c069ad000eb93cc61a5d8c89f0c";
    };
    resources_misc_all = {
      file = "resources_misc_all.zip.99ed79ed868d732d8e9e9a45444b8f003191e3dd";
      sha256 = "187e562403c7544af7162e08baf7677d030ad6f60947c2cdc7dcbcbf0a7a7fe6";
    };
    resources_hidpi_all = {
      file = "resources_hidpi_all.zip.a110d78e994c028dc1c412951e87a0c4e9c819f7";
      sha256 = "5bdb97ec734f035c1d06a59b62980028b1b05b920c544ae3673b1a515d3d507e";
    };
    resources_all = {
      file = "resources_all.zip.213fe769fd8484a0d149453c5655e70c1d13b086";
      sha256 = "769840cdb2b22ad9798a1a3950de2fe82b8b5d3d37389dcc9b1393f77480d67b";
    };
    strings_en_all = {
      file = "strings_en_all.zip.e716a67d7fa91ba70490a6417e25d45c5435e393";
      sha256 = "0c56193fac4fa518eaaac0dc66ecd21a3cee510ece85594b6c308f8d31ee98a3";
    };
    strings_all = {
      file = "strings_all.zip.ad0779a3a2612ae06fe66604b121245d3905fd12";
      sha256 = "5a5370f3b16675cc39d928d8557ff42f4f6caa427ea4d6bc7f98ee31d8ef9513";
    };
    public_all = {
      file = "public_all.zip.10426d0860e311f024654d1f932d4434e6d55a92";
      sha256 = "3cbb29584059934c95145400304319ca9a4a47d54a4978c6ecac1cfad2357847";
    };
    bins_hardware_all = {
      file = "bins_hardware_all.zip.c52878402b36211c3c356c9f4d672aed6e024512";
      sha256 = "e5bbe40a2c496f0bb917e05a650f049c117824b19df592f11faed9cfb6f86f59";
    };
    steamui_websrc_sounds_all = {
      file = "steamui_websrc_sounds_all.zip.74727ca40ef88c5012bb631488fd285418dce825";
      sha256 = "c823bd39d234e7d9a5fdb5ec6605eae3f175e52bb847725e8826ff526a61641c";
    };
    steamui_websrc_movies_all = {
      file = "steamui_websrc_movies_all.zip.40e78cdda48e9a8a74baf614e0cdc7a6b96d26d1";
      sha256 = "885a32533327f0fd5ea98e6c6f13552e965cab4852dad7ce9ccf3d929d726b5b";
    };
    webkit_linuxarm64_linuxarm64 = {
      file = "webkit_linuxarm64_linuxarm64.zip.c1d5fa58a564375f71b34bccaa51c19be1143137";
      sha256 = "b8687e0f20668d24055d8f2e9f6c4fbcbe84fbb99a7bc9de4595530be7029990";
    };
    sdl3_linuxarm64_linuxarm64 = {
      file = "sdl3_linuxarm64_linuxarm64.zip.fc0b788fa83061e2023b181e8593d40867fd034c";
      sha256 = "d6a3b4f81ef3426bf9253f9dd8b8845c71b9939769f0c6db2df8268b9217a7f8";
    };
    codecs_linuxarm64_linuxarm64 = {
      file = "codecs_linuxarm64_linuxarm64.zip.b27e1d78cec034a8c73b0ff1bc6acbe3b8586344";
      sha256 = "8e77a5e4605d7c7b576ce64abf39cfd342aea8d6783e17f2fb91e1c8f4357a0f";
    };
    bins_linuxarm64_linuxarm64 = {
      file = "bins_linuxarm64_linuxarm64.zip.c62d9f8cc1ce96851c06ca718176a4b94a1bb0ee";
      sha256 = "1c29ec264afc7eeaa80942d1dae4b253bbe5d16515a4fd7b98930086b40a055c";
    };
    bins_sdk_linuxarm64_linuxarm64 = {
      file = "bins_sdk_linuxarm64_linuxarm64.zip.fd292466cdeb109a3287435d0b4d7b6c5b7434ab";
      sha256 = "c9dd6ae254d0f9fd39bb013a91c4b090b796df07142893f1460af43c648f0183";
    };
    resource_linuxarm64_linuxarm64 = {
      file = "resource_linuxarm64_linuxarm64.zip.6e5691ac5a1a55a554250468a98c3f8e454fea4a";
      sha256 = "f78280db38d95a74096a00f7d2bc3061286db135e9e61bbf963eb65de39d66fc";
    };
  };
}
